name: Quality checks

# Runs ESLint, Prettier (check-only) and the TypeScript compiler on every
# push and pull-request.  Keeps the main branch free from style and lint
# regressions.

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      # ---------- Lint & Format ------------------------------------------------
      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      # ---------- TypeScript ---------------------------------------------------
      - name: Type-check (tsc)
        run: npm run tsc
